# Generated by Django 4.0.6 on 2022-08-01 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockType', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('onTrip', models.BooleanField(default=False)),
                ('signedOut', models.BooleanField(default=False)),
                ('signedIn', models.BooleanField(default=True)),
                ('name', models.CharField(default='brumsurf', max_length=50)),
                ('studentId', models.CharField(default='0000000', max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('qrCode', models.ImageField(upload_to='')),
                ('url', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('bootAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Glove',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('gloveAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('hoodAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Surfboard',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('surfboardNumber', models.PositiveIntegerField(default=0, unique=True)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Surfskate',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('surfskateNumber', models.PositiveIntegerField(default=0, unique=True)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Wetsuit',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('gender', models.CharField(max_length=6)),
                ('wetsuitNumber', models.PositiveIntegerField(default=0, unique=True)),
            ],
            bases=('App.stockitem',),
        ),
    ]
