# Generated by Django 4.0.6 on 2022-07-20 01:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('Number', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('onTrip', models.BooleanField(default=False)),
                ('signedOut', models.BooleanField(default=False)),
                ('signedIn', models.BooleanField(default=True)),
                ('name', models.CharField(default='brumsurf', max_length=50)),
                ('studentId', models.CharField(default='0000000', max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='wetsuit',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('wetsuitSize', models.CharField(choices=[('4', 'Four'), ('6', 'Six'), ('8', 'Eight'), ('10', 'Ten'), ('12', 'Twelve'), ('14', 'Fourteen'), ('16', 'Sixteen')], max_length=10)),
            ],
            bases=('App.stockitem',),
        ),
    ]
