# Generated by Django 4.0.6 on 2022-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_wetsuit_wetsuitsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
