# Generated by Django 4.0.6 on 2022-08-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_boot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boot',
            options={'ordering': ['-pk']},
        ),
    ]
