# Generated by Django 4.0.6 on 2022-07-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_stockitem_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surfboard',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('surfboardNumber', models.PositiveIntegerField(default=0, unique=True)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='number',
        ),
        migrations.AddField(
            model_name='wetsuit',
            name='wetsuitNumber',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
