# Generated by Django 4.0.6 on 2022-08-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_boot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['size']},
        ),
    ]
