# Generated by Django 4.0.6 on 2022-07-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_surfboard_remove_stockitem_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('bootAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Glove',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('gloveAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('hoodAmount', models.PositiveIntegerField(default=0)),
            ],
            bases=('App.stockitem',),
        ),
        migrations.CreateModel(
            name='Surfskate',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.stockitem')),
                ('surfskateNumber', models.PositiveIntegerField(default=0, unique=True)),
            ],
            bases=('App.stockitem',),
        ),
    ]
