# Generated by Django 4.0.6 on 2022-08-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_stockitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ('size',)},
        ),
    ]
