# Generated by Django 4.0.6 on 2022-08-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_stockitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boot',
            options={'ordering': ['size']},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={},
        ),
    ]
